### ISSUE TITLE
List of licenses should probably pull from master licenses list

### ISSUE THREAD

**Issue by danfowler** [trickvi/datapackage#43] opened 2015-08-21 15:07 UTC
Hello,

Currently, there is a static list of licenses found here:

https://github.com/trickvi/datapackage/tree/master/datapackage/data/

It would probably make sense to instead read from the master list of licenses found here: https://github.com/okfn/licenses/blob/master/licenses/groups/all.json

I tried to use this library to load a [valid data package](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fos-data%2Fboost-armenia%2F848c5c18d5dca90659ba21e085a77b62e5ee330e%2Fdatapackage.json) and it complained:

    License string must be an Open Definition License ID

Cheers,

Dan

**Comment by trickvi** [comment] 2015-08-21 16:16
Yes. Agreed although I'd like to keep an up to date cache of licenses so we don't have to rely on Internet connections

**Comment by vitorbaptista** [comment] 2016-04-18 10:58
This is a duplicate of https://github.com/frictionlessdata/datapackage-py/issues/12. We can close this and track the issue over there.

**Comment by trickvi** [comment] 2016-05-02 20:58
Since the repo will be maintained by the frictionlessdata and this is being tracked there. I'm therefore closing this issue.

**Closed by trickvi** 2016-05-02 20:58 UTC
